version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # pour accéder depuis ton PC / WSL

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"  # accès via navigateur : http://localhost:8081
    depends_on:
      - db

volumes:
  postgres_data:
